rest:
  routes:
    - url: "/healthcheck"
      methods: ["GET"]
      handler: "healthcheck"
      action: "get"
      params: []
    # - url: "/login"
    #   methods: ["POST"]
    #   handler: "auth"
    #   action: "login"
    - url: "/user/signup"
      methods: ["POST"]
      handler: "user_account"
      action: "register_user"
      params:
      - name: "email"
        type: "str"
        required: true
      - name: "password"
        type: "str"
        required: true
      - name: "display_name"
        type: "str"
        required: true
    - url: "/user/delete"
      methods: ["POST"]
      handler: "user_account"
      action: "delete_user"
      params:
      - name: "uid"
        type: "str"
        required: true

  # - url: "/users"
  #   methods: ["POST"]
  #   handler: "user"
  #   action: "create"
